FROM openjdk:11 as builder

WORKDIR /app

COPY . .

RUN sed -i 's/\r$//' ./gradlew && chmod +x ./gradlew

RUN ./gradlew buildFatJar

FROM openjdk:11

COPY --from=builder /app/build/libs/api_gateway.jar api_gateway.jar

CMD ["java", "-jar", "api_gateway.jar"]

EXPOSE 8080