package com.angus.api_gateway.util

enum class APIs(val value: String) {
    RESTAURANT_API("RESTAURANT_API"),
    DELIVERY_API("DELIVERY_API"),
    IDENTITY_API("IDENTITY_API"),
    NOTIFICATION_API("NOTIFICATION_API"),
    IMGUR_API("IMGUR_API"),
    LOCATION_API("LOCATION_API"),
    CHAT_API("CHAT_API")
}